version: "3.1"
services:

    mysql:
      image: mariadb:10.0
      volumes:
        - ./data:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=villahide
        - MYSQL_DATABASE=villahide
      ports:
        - "7002:3306"

    nginx:
      image: nginx:alpine
      working_dir: /app
      volumes:
        - .:/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
      ports:
        - "7001:80"

    php:
      build: docker/php
      working_dir: /app
      volumes:
        - .:/app
      depends_on:
        - mysql
      environment:
        PHP_IDE_CONFIG: serverName=localhost
